export const gameToPokedexMap: { [key: string]: string } = {
    'Sword & Shield': 'galar',
    'Scarlet & Violet': 'paldea',
    'Legends: Arceus': 'hisui',
    'Ultra Sun & Ultra Moon': 'updated-alola',
    'Sun & Moon': 'original-alola',
    'Brilliant Diamond & Shining Pearl': 'extended-sinnoh',
    "Let's Go, Pikachu & Eevee": 'kanto-lgpe',
    'Omega Ruby & Alpha Sapphire': 'updated-hoenn',
    'X & Y': 'kalos-central',
    'Black 2 & White 2': 'unova-b2w2',
    'Black & White': 'original-unova',
    'HeartGold & SoulSilver': 'johto-hgss',
    'Diamond, Pearl & Platinum': 'extended-sinnoh',
    'FireRed & LeafGreen': 'kanto-frlg',
    'Ruby, Sapphire & Emerald': 'hoenn',
    'Gold, Silver & Crystal': 'original-johto',
    'Red, Blue & Yellow': 'original-kanto',
};
